apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-03-kustomize
resources:
  - ../../base
configMapGenerator:
  - name: demo-config
    literals:
      - message=hello from Kustomize v1
secretGenerator:
  - name: demo-secret
    literals:
      - token=fake-kustomize-token-v1
generatorOptions:
  disableNameSuffixHash: false
  immutable: true
  labels:
    app.kubernetes.io/part-of: versioned-config-demo

