apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: checksum-demo
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  message: {{ .Values.config.message | quote }}

